### ISSUE TITLE
Define Baroes Director without hiera 

### ISSUE THREAD

**Issue by Kurt-O** [kjetilho/rl-bareos#2]
I'd like to run your puppet module in our company, but we don't use hiera. Is there a way that you can update your code to make the three parameters definable via a variable? If you could do this, both ways will be available and it would help me a lot.

Kind regards 
Kurt

**Comment by kjetilho** [comment]
sorry about the late reply.! (strange that I didn't get a notification.)
you are talking about bareos::secret and bareos::schedules, I take it?  yes, I guess I can.
(if there is a third, please tell me.)

**Comment by kjetilho** [comment]
I found the third instance ;-)
